### ISSUE TITLE
環境変数の追加のコマンド

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/issues#4]
## 質問の内容

> 環境変数の追加
> 　OpenFOAMのbashrcをターミナル起動時に読み込むように~/.bashrcに登録します。
> 
> echo "export ~/OpenFOAM/OpenFOAM-dev/etc/.bashrc" >> ~/.bashrc
> . ~/.bashrc

この部分についてですがexportは構文として誤っており、"~/OpenFOAM/OpenFOAM-dev/etc/.bashrc"は存在しないため、以下が正しいと思いますがいかがでしょうか。

`echo "source ~/OpenFOAM/OpenFOAM-dev/etc/.bashrc" >> ~/.bashrc `

## OSの種類/ディストリ/バージョン

*   Ubuntu 18.04 LTS

**Comment by tkoyama010** [comment]
追加報告します。
`~/OpenFOAM/OpenFOAM-dev/etc/.bashrc`
は
`~/OpenFOAM/OpenFOAM-dev/etc/bashrc`
です。

**Comment by inabower** [comment]
エラーの原因は
`~/OpenFOAM/OpenFOAM-dev/etc/.bashrc` -> `~/OpenFOAM/OpenFOAM-dev/etc/bashrc`
かと思われます。"."が要りませんでした。失礼しました。

exportとsourceについてはどちらも同じように動作するように認識していましたがそうではないのでしょうか。

**Comment by tkoyama010** [comment]
> exportとsourceについてはどちらも同じように動作するように認識していましたがそうではないのでしょうか。

私の認識間違えかもしれませんのでパスを修正して再実行します。

**Comment by inabower** [comment]
今確認したところexportでは動作しませんでした。
sourceに修正致します

**Comment by tkoyama010** [comment]
[![LGTM](https://lgtm.in/p/SRPmK9kqq)](https://lgtm.in/i/SRPmK9kqq)

https://github.com/OpenFOAM-jp/issues/wiki/%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%89%8B%E9%A0%86
